### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by ph1l** [SignalK/signalk-server-java#33]
Build Failure @ 1c2c80daa98a582415e7c7b6366916357eeabe5f

```
elektron@signalk:~/signalk-server-java$ mvn -X -Dsignalk.build=dev install
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_112, vendor: Oracle Corporation
Java home: /usr/lib/jvm/oracle-java8-jdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.7.0-1-amd64", arch: "amd64", family: "unix"
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building signalk-server-java 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ signalk-server-java ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 4 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.0:compile (default-compile) @ signalk-server-java ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 67 source files to /home/elektron/signalk-server-java/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/elektron/signalk-server-java/src/main/java/nz/co/fortytwo/signalk/processor/IncomingSecurityFirewall.java:[29,1] cannot find symbol
  symbol:   static DEMO
  location: class
[ERROR] /home/elektron/signalk-server-java/src/main/java/nz/co/fortytwo/signalk/processor/SourceToSourceRefProcessor.java:[29,1] cannot find symbol
  symbol:   static label
  location: class
[ERROR] /home/elektron/signalk-server-java/src/main/java/nz/co/fortytwo/signalk/server/RouteManager.java:[27,1] cannot find symbol
  symbol:   static DEMO
  location: class
[ERROR] /home/elektron/signalk-server-java/src/main/java/nz/co/fortytwo/signalk/server/RouteManager.java:[430,55] cannot find symbol
  symbol:   variable DEMO
  location: class nz.co.fortytwo.signalk.server.RouteManager
[ERROR] /home/elektron/signalk-server-java/src/main/java/nz/co/fortytwo/signalk/processor/SourceToSourceRefProcessor.java:[67,64] cannot find symbol
  symbol:   variable label
  location: class nz.co.fortytwo.signalk.processor.SourceToSourceRefProcessor
[ERROR] /home/elektron/signalk-server-java/src/main/java/nz/co/fortytwo/signalk/processor/SourceToSourceRefProcessor.java:[76,95] cannot find symbol
  symbol:   variable label
  location: class nz.co.fortytwo.signalk.processor.SourceToSourceRefProcessor
[ERROR] /home/elektron/signalk-server-java/src/main/java/nz/co/fortytwo/signalk/processor/IncomingSecurityFirewall.java:[93,50] cannot find symbol
  symbol:   variable DEMO
  location: class nz.co.fortytwo.signalk.processor.IncomingSecurityFirewall
[INFO] 7 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.260 s
[INFO] Finished at: 2016-11-22T20:38:35-08:00
[INFO] Final Memory: 34M/82M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.0:compile (default-compile) on project signalk-server-java: Compilation failure: Compilation failure:
[ERROR] /home/elektron/signalk-server-java/src/main/java/nz/co/fortytwo/signalk/processor/IncomingSecurityFirewall.java:[29,1] cannot find symbol
[ERROR] symbol:   static DEMO
[ERROR] location: class
[ERROR] /home/elektron/signalk-server-java/src/main/java/nz/co/fortytwo/signalk/processor/SourceToSourceRefProcessor.java:[29,1] cannot find symbol
[ERROR] symbol:   static label
[ERROR] location: class
[ERROR] /home/elektron/signalk-server-java/src/main/java/nz/co/fortytwo/signalk/server/RouteManager.java:[27,1] cannot find symbol
[ERROR] symbol:   static DEMO
[ERROR] location: class
[ERROR] /home/elektron/signalk-server-java/src/main/java/nz/co/fortytwo/signalk/server/RouteManager.java:[430,55] cannot find symbol
[ERROR] symbol:   variable DEMO
[ERROR] location: class nz.co.fortytwo.signalk.server.RouteManager
[ERROR] /home/elektron/signalk-server-java/src/main/java/nz/co/fortytwo/signalk/processor/SourceToSourceRefProcessor.java:[67,64] cannot find symbol
[ERROR] symbol:   variable label
[ERROR] location: class nz.co.fortytwo.signalk.processor.SourceToSourceRefProcessor
[ERROR] /home/elektron/signalk-server-java/src/main/java/nz/co/fortytwo/signalk/processor/SourceToSourceRefProcessor.java:[76,95] cannot find symbol
[ERROR] symbol:   variable label
[ERROR] location: class nz.co.fortytwo.signalk.processor.SourceToSourceRefProcessor
[ERROR] /home/elektron/signalk-server-java/src/main/java/nz/co/fortytwo/signalk/processor/IncomingSecurityFirewall.java:[93,50] cannot find symbol
[ERROR] symbol:   variable DEMO
[ERROR] location: class nz.co.fortytwo.signalk.processor.IncomingSecurityFirewall
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.0:compile (default-compile) on project signalk-server-java: Compilation failure
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:745)
        at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:118)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by rob42** [comment]
You need to update signalk-core and build that first. Probably ' clean' then 'build'

**Comment by ph1l** [comment]
oh, right, I forgot about that..

**Comment by ph1l** [comment]
works :-)
